### ISSUE TITLE
Warning of potential momory leak when using gtLogOnce

### ISSUE THREAD

**Issue by jensschmeink** [dlr-gtlab/gt-logging#139]
If the gtLogOnce function is used my IDE gives me a warning of potential memory leakage.
Is there the possibility to get rid of this warning?

![grafik](https://github.com/user-attachments/assets/4f49c5bb-43c8-4325-8474-b9cc26dc66be)

**Comment by mariusalexander** [comment]
I am quite sure this is a **false-positive** of clang analyzer. Further, the warning is raised in MSVCs STL implementation, so there is little we can do.

If anyone actually does find a memory leak or a persistent fix of this warning feel free to reopen this issue or a PR.
