### ISSUE TITLE
Consider adding the verbosity of a non-silent message level to the ouput

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gt-logging#51]
In GitLab by @mariusalexander on May 25, 2023, 11:32

I have recieved the request to append the verbosity level to the output for non-silent messages (i.e. verbosity >= medium).

Example:
```c++
gtDebug().verbose() << "Hello World!"
// DEBUG [<TIME>] [<VERBOSE>] [<ID>] Hello World!
```

However, this would require an ABI change (and an API change as far as I can tell). I am not to sure whether this is worth it. If this feature gets more attention we'll might look into this more. For now this is low priority (IMHO).

If we do decide to implement this, issue #59 becomes relevant

**Comment by mariusalexander** [comment]
Closed as not planned, please reopen if this feature is actively needed
