### ISSUE TITLE
Consider implementing option to log a message to a single destination

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/gt-logging#55]
In GitLab by @mariusalexander on Jun 12, 2023, 13:20

There has been the request to log a message to a single destination. While this is techinally possible, using the `write` mthod of an destination, the current time, id and other flags are not automatically processed like they are using the `gt::log::Logger::Helper` class. 

Maybe we could provide a macro like `gtLogTo` (or `gtLogToDest`/`gtLogDest`) which accepts a destination pointer as well as the logging level. It could be used like this:

```cpp
auto myDestPtr = gt::log::makeDebugOutputDestination();
auto* myDest = myDestPtr.get();  // access ptr before it has been moved
gt::log::Logger::instance().addDestination("my_dest", std::move(myDestPtr));

gtLogTo(myDest, Debug) << "Hello world"; // Debug will denote the logging level (to avoid having to declare multiple new macros)
```

**Comment by mariusalexander** [comment]
I'll close this issue for now as the feature is not needed currently (and the PR #120 has been opened for ages without progress). If anybody wants this feature, just reopen this issue.
